run_dir = "simulator_run" # where reads, logs, pafs etc. will be written to
n_channels = 512
# n_channels = 4
acceleration_factor = 10
run_duration = 300.0

#################################################
# Optional arguments
#################################################

# reads_file = "nanosim_reads/perfect_reads_seed1_aligned_reads.fasta"
ref_genome_path = "data/chm13v2.0_normalized1000000firsttwo.fa.gz"
sim_params_file = "sim_params.dill"
rotating = true
mux_scan_period = 100 # seconds, accounting for acceleration
mux_scan_duration = 10 # seconds

# readfish params
readfish_config_file = "configs/readfish_enrich_chr1.toml"
# readfish_method = "unblock_all"
readfish_method = "targeted_seq"

#################################################
# Parameter extraction arguments
#################################################
seqsum_param_extr_file = "data/20190809_zymo_seqsum.txt"
n_channels_full = 512
gap_sampler_type = "random"