run_dir = "simulator_run" # where reads, logs, pafs etc. will be written to
n_channels = 512
acceleration_factor = 10
run_duration = 3600.0
# run_duration = 1000

#################################################
# Optional arguments
#################################################

# reads_file = "nanosim_reads/perfect_reads_seed1_aligned_reads.fasta"
reads_len_range = [12000, 16000]
ref_genome_path = "data/chm13v2.0_normalized3chroms.fa.gz"
sim_params_file = "sim_params.dill"
rotating_writeout = true
mux_scan_period = 240 # seconds
mux_scan_duration = 40 # seconds

use_grpc = true

# readfish params
readfish_config_file = "configs/readfish_enrich_chr20.toml"
# readfish_method = "unblock_all"
readfish_method = "targeted_seq"

#################################################
# Parameter extraction arguments
#################################################
seqsum_param_extr_file = "data/20190809_zymo_seqsum.txt"
n_channels_full = 512
gap_sampler_type = "sampler_per_window"